### ISSUE TITLE
Geocoder does not zoom to the location correctly

### ISSUE THREAD

**Issue by senturank** [Dominique92/ol-geocoder#228] opened 2020-11-11 17:47 UTC
Everything was working fine until about 2 weeks back when, after selecting an address the map zooms to some irrelevant location. We have been trying to fix without any luck. I noticed that the same issue occurs in the jsfiddle link as well. Did something change recently?

**Comment by jonataswalker** [comment] 2020-11-11 18:17
Do you mean this fiddle?

http://jsfiddle.net/jonataswalker/c4qv9afb/

**Comment by senturank** [comment] 2020-11-11 18:21
Yes. Thats the one

**Comment by jonataswalker** [comment] 2020-11-12 10:47
Well, it looks okay for me, would you mind to create a step by step to reproduce?

**Comment by senturank** [comment] 2020-11-12 11:04
I have recorded my screen while trying to use the jsfiddle.

https://drive.google.com/file/d/1QoEGVwUQboLwXb2jD0eE762A0oG2XoKf/view?usp=sharing

We have been using this api for the last 4 months on OSM (**_Thanks !!!_**), but it suddenly started misbehaving about 3 weeks back and it zooms to irrelevant locations (Though on zooming out, you see that the marker is placed correctly) . I checked the jsfiddle which we used as our reference and it seemed to have the same issue. 

I noticed something really weird. We are facing this issue across computers and browsers in our implementation, but the jsfiddle seems to have this issue only on firefox and not on chrome.

**Comment by jonataswalker** [comment] 2020-11-23 10:51
Are you able to investigate if this commit (https://github.com/jonataswalker/ol-geocoder/commit/0f940fa6417b1de1387502e14dc689f02a7fa7d3) is the reason?

**Comment by Dominique92** [comment] 2021-04-11 14:27
YES ! when I remove this line, I have no more problems
bbox: result.boundingbox,

Note : my problem was that it zoom to level 1 when integrated with a phpBB forum.
When operated without phpBB context, it works well
I did not success to identify what part of phpBB interfer with Geocoder

**Comment by Dominique92** [comment] 2023-09-05 19:52
Closed in https://github.com/Dominique92/ol-geocoder/releases/tag/v4.3.0

**Closed by Dominique92** 2023-09-05 19:52 UTC
Labels: need feedback
